services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    build: ./server
    # ports:
      # - 3000:3000
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - server
    ports:
      - 3000:3000  

  # client:
  #   build: ./client
  #   depends_on:
  #     - server 